### ISSUE TITLE
daily-poem module: double-click-left 不起反应

### ISSUE THREAD

**Issue by KuringM** [Yucklys/polybar-nord-theme#9]

**Comment by ghost** [comment]
provide a description to your problem

**Comment by KuringM** [comment]
> provide a description to your problem

```
click-left = polybar-msg -p %pid% hook daily-poem 1
#double-click-left = polybar-msg -p %pid% hook daily-poem 1
```
This is in my daily-poem module.
I can click left this module to get a new poem,when i use the `click-left`.
But, I can't get a new poem ,when i use the`double-click-left=....`

**Comment by Yucklys** [comment]
> > provide a description to your problem
> 
> ```
> click-left = polybar-msg -p %pid% hook daily-poem 1
> #double-click-left = polybar-msg -p %pid% hook daily-poem 1
> ```
> 
> This is in my daily-poem module. I can click left this module to get a new poem,when i use the `click-left`. But, I can't get a new poem ,when i use the`double-click-left=....`

I think the problem is due to polybar itself. The default time interval for double-click is 400ms. You can try again but do the double click faster, it should work as long as you setup your own token.
If the default setting is not comfortable for you, you can set `double-click-interval` inside `bar/nord-down` or `bar/base` to a right value.
For detailed explanation, you can go and check [polybar #1441](https://github.com/polybar/polybar/issues/1441).

I am working on a improved poem module with auto updated Token, which will be finished in two or three days. So if `double-click-interval` does not solve the problem, you can check the new version when I push the update.

**Comment by KuringM** [comment]
> > > provide a description to your problem
> > 
> > 
> > ```
> > click-left = polybar-msg -p %pid% hook daily-poem 1
> > #double-click-left = polybar-msg -p %pid% hook daily-poem 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is in my daily-poem module. I can click left this module to get a new poem,when i use the `click-left`. But, I can't get a new poem ,when i use the`double-click-left=....`
> 
> I think the problem is due to polybar itself. The default time interval for double-click is 400ms. You can try again but do the double click faster, it should work as long as you setup your own token. If the default setting is not comfortable for you, you can set `double-click-interval` inside `bar/nord-down` or `bar/base` to a right value. For detailed explanation, you can go and check [polybar #1441](https://github.com/polybar/polybar/issues/1441).
> 
> I am working on a improved poem module with auto updated Token, which will be finished in two or three days. So if `double-click-interval` does not solve the problem, you can check the new version when I push the update.

`double-click-interval` does not solve this problem, i'm looking forward to your new version.

**Comment by Yucklys** [comment]
I have pushed a new version of daily-poem. Just use the default setting should work. For more configuration check README. I use `click-right` instead of double click to update poem. However, you can try if this version fix the double-click problem on your machine.

**Comment by KuringM** [comment]
> I have pushed a new version of daily-poem. Just use the default setting should work. For more configuration check README. I use click-right instead of double click to update poem. However, you can try if this version fix the double-click problem on your machine.

A good new version, I switch to this. But the double-click problem still exists on my machine, I think the problem is due to polybar itself. 
Thanks for you help!
